#ifndef PLATFORMS_NEMORA_PORTABLE_DEFAULT_ADDRESSES_H_
#define PLATFORMS_NEMORA_PORTABLE_DEFAULT_ADDRESSES_H_
//
// Nemora dedicated port. Filtered by NIC. See //depot/eng/ports.
#define DEFAULT_ADDRESSES_RX_PORT 3959

#endif  // PLATFORMS_NEMORA_PORTABLE_DEFAULT_ADDRESSES_H_
